# Generated by Django 3.1.5 on 2021-01-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_article_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='email',
            field=models.EmailField(default='abc@mgail.com', max_length=254),
            preserve_default=False,
        ),
    ]
